#!/usr/bin/env bash
# quickstart.sh — Zero-config setup for Research-Agent
# Usage: bash scripts/quickstart.sh

set -e

BOLD='\033[1m'; CYAN='\033[0;36m'; GREEN='\033[0;32m'
YELLOW='\033[1;33m'; RED='\033[0;31m'; RESET='\033[0m'

info()    { echo -e "${CYAN}▶${RESET} $*"; }
ok()      { echo -e "${GREEN}✓${RESET} $*"; }
warn()    { echo -e "${YELLOW}!${RESET} $*"; }
err()     { echo -e "${RED}✗${RESET} $*" >&2; }
ask()     { echo -e "${BOLD}?${RESET} $*"; }
section() { echo -e "\n${BOLD}── $* ${RESET}"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║        Research-Agent Quickstart         ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── Preflight ─────────────────────────────────────────────────────────────────
section "Checking requirements"

if ! command -v docker &>/dev/null; then
    err "Docker not found. Install from https://docs.docker.com/get-docker/ and re-run."
    exit 1
fi
ok "Docker found ($(docker --version | cut -d' ' -f3 | tr -d ','))"

if ! docker compose version &>/dev/null; then
    err "Docker Compose v2 not found. Update Docker Desktop or install the plugin."
    exit 1
fi
ok "Docker Compose v2 found"

# ── LLM backend ───────────────────────────────────────────────────────────────
section "LLM backend"
echo ""
echo "  1) Local Ollama (included — no API key needed, ~1 GB model download)"
echo "  2) OpenAI        (needs OPENAI_API_KEY, fastest, no local model)"
echo "  3) Any OpenAI-compatible API (LM Studio, Together, Groq, etc.)"
echo ""
ask "Choose [1/2/3] (default: 1):"
read -r llm_choice
llm_choice="${llm_choice:-1}"

COMPOSE_FILE="docker-compose.full.yml"
OLLAMA_MODEL="qwen2.5:1.5b"
OPENAI_API_KEY=""
OPENAI_BASE_URL=""
OLLAMA_BASE_URL="http://ollama:11434"

case "$llm_choice" in
  2)
    ask "Paste your OpenAI API key (sk-...):"
    read -r OPENAI_API_KEY
    if [[ -z "$OPENAI_API_KEY" ]]; then err "Key cannot be empty."; exit 1; fi
    OLLAMA_MODEL="gpt-4o-mini"
    OLLAMA_BASE_URL=""
    COMPOSE_FILE="docker-compose.yml"
    ok "Will use OpenAI (gpt-4o-mini)"
    ;;
  3)
    ask "Base URL of your API (e.g. http://localhost:1234/v1):"
    read -r OPENAI_BASE_URL
    ask "API key (press Enter if not required):"
    read -r OPENAI_API_KEY
    ask "Model name (e.g. llama-3.2-3b-instruct):"
    read -r OLLAMA_MODEL
    OLLAMA_BASE_URL="${OPENAI_BASE_URL}"
    COMPOSE_FILE="docker-compose.yml"
    ok "Will use custom API at ${OPENAI_BASE_URL}"
    ;;
  *)
    section "Model size"
    echo ""
    echo "  s) Small  — qwen2.5:1.5b (~1 GB)  Fast, good for most topics"
    echo "  m) Medium — qwen2.5:3b   (~2 GB)  Better reasoning"
    echo "  l) Large  — qwen3:14b    (~9 GB)  Best quality, needs 16 GB RAM"
    echo ""
    ask "Choose [s/m/l] (default: s):"
    read -r model_choice
    case "${model_choice:-s}" in
      m) OLLAMA_MODEL="qwen2.5:3b"  ;;
      l) OLLAMA_MODEL="qwen3:14b"   ;;
      *) OLLAMA_MODEL="qwen2.5:1.5b" ;;
    esac
    ok "Will use local Ollama with ${OLLAMA_MODEL}"
    ;;
esac

# ── Optional API keys ─────────────────────────────────────────────────────────
section "Optional API keys (press Enter to skip)"
echo ""
warn "Tavily gives better web search results (free tier: 1000 req/month)"
warn "Get a key at https://tavily.com — or press Enter to use DuckDuckGo instead"
echo ""
ask "TAVILY_API_KEY (optional):"
read -r TAVILY_API_KEY

ask "GITHUB_TOKEN (optional — improves GitHub source results):"
read -r GITHUB_TOKEN

# ── Write .env ────────────────────────────────────────────────────────────────
section "Creating .env"

cat > .env <<EOF
# Generated by quickstart.sh
OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
OLLAMA_MODEL=${OLLAMA_MODEL}
OPENAI_API_KEY=${OPENAI_API_KEY}
TAVILY_API_KEY=${TAVILY_API_KEY}
GITHUB_TOKEN=${GITHUB_TOKEN}
LOG_LEVEL=INFO
EOF

ok ".env created"

# ── Launch ────────────────────────────────────────────────────────────────────
section "Starting Research-Agent"
echo ""

if [[ "$COMPOSE_FILE" == "docker-compose.full.yml" ]]; then
    info "Pulling Ollama image and model ${OLLAMA_MODEL} (first run — grab a coffee)..."
fi

OLLAMA_MODEL="$OLLAMA_MODEL" docker compose -f "$COMPOSE_FILE" up --build -d

echo ""
ok "Research-Agent is starting up!"
echo ""
echo -e "  ${BOLD}Open:${RESET} http://localhost:8501"
echo ""
echo -e "  ${CYAN}Logs:${RESET}  docker compose -f $COMPOSE_FILE logs -f"
echo -e "  ${CYAN}Stop:${RESET}  docker compose -f $COMPOSE_FILE down"
echo ""
